### ISSUE TITLE
Project Management - Basic Setup

### ISSUE THREAD

**Issue by tasajovanovic** [alptium/personal-fitness#1]

**Comment by valentinajemuovic** [comment]
@tasajovanovic, this is good, but you missed the step of ensuring that all your team members had submitted a Project Approval Request.

**Comment by tasajovanovic** [comment]
@valentinacupac  they are notified, and it will be updated

**Comment by valentinajemuovic** [comment]
@tasajovanovic, I still didn't receive this from @SasaOrca, please handle that, so that we can close this PM ticket...

**Comment by valentinajemuovic** [comment]
@tasajovanovic, @SasaOrca has completed his ticket, so closing this ticket too.
